# This action fetches the latest version of QGIS, builds it, and extracts the
# Python components into a new branch.
# It then performs basic cleanup and automated fixes in additional commits and
# finally creates a PR with the updated type stubs.
#
# Manual review and tidying up is usually required before merging.

name: Generate type stubs

# Only manual trigger supported for now
on:
  workflow_dispatch: {}
  push:
    branches:
      - stubgen-ci

jobs:
  # Create the branch used for the PR
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: Configure git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Create branch
        run: |
          git checkout -b stubgen/${{ github.run_id }}
          git push --set-upstream origin stubgen/${{ github.run_id }}

  # Build QGIS in a docker container and extract the Python components to the
  # new branch
  build-qgis:
    runs-on: ubuntu-latest
    needs: create-branch
    steps:
      - uses: actions/checkout@v2
        with:
          ref: stubgen/${{ github.run_id }}
          fetch-depth: 0

      - name: Fetch latest QGIS
        run: |
          docker image pull qgis/qgis:latest

      - name: Build QGIS
        run: |
          docker run --name qgis-stubgen qgis/qgis:latest sh -c "cd /QGIS/build && cmake . && ninja"

      - name: Extract Python modules
        run: |
          docker cp qgis-stubgen:/QGIS/build/output/python/qgis .

      - name: Remove non-Python files
        run: |
          python scripts/delete-non-python.py qgis

      - name: Configure git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit changes
        run: |
          git add qgis
          git commit -m "Extracted Python modules from QGIS build"
          git push origin stubgen/${{ github.run_id }}

  # Perform automated replacements and tidy-up on the new stubs
  clean-stubs:
    runs-on: ubuntu-latest
    needs: build-qgis
    steps:
      - uses: actions/checkout@v2
        with:
          ref: stubgen/${{ github.run_id }}
          fetch-depth: 0

      - name: Configure git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Step 1 - Replace PyQt with PyQt5
        run: |
          python scripts/search-and-replace.py qgis "from qgis.PyQt" "from PyQt5"
          rm -rf qgis/PyQt
          git add -A
          git commit -m "Replace qgis.PyQt references with PyQt5"

      - name: Step 2 - Replace sip imports with dummy
        run: |
          python scripts/search-and-replace.py qgis "import sip" "sip: typing.Any = ..."

      - name: Push changes
        run: |
          git push origin stubgen/${{ github.run_id }}
